language: nix
env:
    - PYTHON_VERSION=27
    - PYTHON_VERSION=34
    - PYTHON_VERSION=35
    - PYTHON_VERSION=36

before_install:
    - mkdir -p $HOME/.nixpkgs
    - cp travis.nix $HOME/.nixpkgs/config.nix
    - nix-env -i all
    - nix-env -iA nixpkgs.python${PYTHON_VERSION}
    - pip3 install --user tox || pip install --user tox

script:
    - tox -e py${PYVERSION}-test